# @format

title: 我的个人博客
email: your-email@example.com
description: >-
    这是我使用Jekyll和GitHub Pages搭建的个人博客。
baseurl: "" # 如果您的站点位于子目录，则需要在此处添加，例如 "/blog"
url: "" # 例如 https://username.github.io
twitter_username: your-twitter-username
github_username: your-github-username

# 构建设置
markdown: kramdown
theme: minima
plugins:
    - jekyll-feed
    - jekyll-seo-tag

# 排除文件
exclude:
    - Gemfile
    - Gemfile.lock
    - node_modules
    - vendor
    - .gitignore
