# @format

# 站点配置
title: yishan's WORLD
email: your-email@example.com
description: >-
    欢迎来到我的个人博客，这里记录我的思考、学习和生活。
baseurl: "" # 如果您的站点位于子目录，则需要在此处添加，例如 "/blog"
url: "" # 例如 https://username.github.io
github_username: your-github-username

# 构建设置
markdown: kramdown
theme: minima
plugins:
    - jekyll-feed
    - jekyll-seo-tag

# 页面默认设置
defaults:
    - scope:
          path: ""
          type: "posts"
      values:
          layout: "post"
          author: "yishan"
    - scope:
          path: ""
      values:
          layout: "default"

# 排除文件
exclude:
    - Gemfile
    - Gemfile.lock
    - node_modules
    - vendor
    - .gitignore
